export const actionTypes = {
  ADD_TO_CART: "ADD_TO_CART",
  TOGGLE_CART: "TOGGLE_CART",
  DELETE_ITEM: "DELETE_ITEM",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  LOGOUT: "LOGOUT",
  REGISTER_SUCCESS: "REGISTER_SUCCESS",
};
